export const CONTACT_FORM_REQUEST = 'CONTACT_FORM_REQUEST';
export const CONTACT_FORM_REQUEST_SUCCESS = 'CONTACT_FORM_REQUEST_SUCCESS';
export const CONTACT_FORM_REQUEST_FAILURE = 'CONTACT_FORM_REQUEST_FAILURE';